# -*- coding: utf-8 -*-
"""Project4_AI_Text_Recognition_System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxLKgEeFvsnYAhjAomFXy1CBZpTyWole
"""

# =====================================
# Project 4 - AI Text Recognition System
# =====================================

print("===== AI TEXT RECOGNITION SYSTEM =====")

text = input("Enter any text: ")

print("\nText Recognized Successfully!")

print("\nYou Entered:")
print(text)

print("\nAnalysis")
print("----------------------")
print("Total Words      :", len(text.split()))
print("Total Characters :", len(text))
print("Uppercase        :", text.upper())
print("Lowercase        :", text.lower())

print("\n===== PROJECT COMPLETED =====")
print("Project Name : AI Text Recognition System")
print("Concept      : Basic Text Recognition")
print("Language     : Python")
print("Status       : Successfully Completed")